# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: im_protobuf.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='im_protobuf.proto',
  package='protobuf',
  syntax='proto3',
  serialized_options=b'\n\031io.grpc.examples.protobufB\rProtobufProtoP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11im_protobuf.proto\x12\x08protobuf\"4\n\x13QueryUsersOnlineReq\x12\r\n\x05\x61ppId\x18\x01 \x01(\r\x12\x0e\n\x06userId\x18\x02 \x01(\t\"F\n\x13QueryUsersOnlineRsp\x12\x0f\n\x07retCode\x18\x01 \x01(\r\x12\x0e\n\x06\x65rrMsg\x18\x02 \x01(\t\x12\x0e\n\x06online\x18\x03 \x01(\x08\"q\n\nSendMsgReq\x12\x0b\n\x03seq\x18\x01 \x01(\t\x12\r\n\x05\x61ppId\x18\x02 \x01(\r\x12\x0e\n\x06userId\x18\x03 \x01(\t\x12\x0b\n\x03\x63ms\x18\x04 \x01(\t\x12\x0c\n\x04type\x18\x05 \x01(\t\x12\x0b\n\x03msg\x18\x06 \x01(\t\x12\x0f\n\x07isLocal\x18\x07 \x01(\x08\"@\n\nSendMsgRsp\x12\x0f\n\x07retCode\x18\x01 \x01(\r\x12\x0e\n\x06\x65rrMsg\x18\x02 \x01(\t\x12\x11\n\tsendMsgId\x18\x03 \x01(\t\"c\n\rSendMsgAllReq\x12\x0b\n\x03seq\x18\x01 \x01(\t\x12\r\n\x05\x61ppId\x18\x02 \x01(\r\x12\x0e\n\x06userId\x18\x03 \x01(\t\x12\x0b\n\x03\x63ms\x18\x04 \x01(\t\x12\x0c\n\x04type\x18\x05 \x01(\t\x12\x0b\n\x03msg\x18\x06 \x01(\t\"C\n\rSendMsgAllRsp\x12\x0f\n\x07retCode\x18\x01 \x01(\r\x12\x0e\n\x06\x65rrMsg\x18\x02 \x01(\t\x12\x11\n\tsendMsgId\x18\x03 \x01(\t\"\x1f\n\x0eGetUserListReq\x12\r\n\x05\x61ppId\x18\x01 \x01(\r\"A\n\x0eGetUserListRsp\x12\x0f\n\x07retCode\x18\x01 \x01(\r\x12\x0e\n\x06\x65rrMsg\x18\x02 \x01(\t\x12\x0e\n\x06userId\x18\x03 \x03(\t2_\n\tAccServer\x12R\n\x10QueryUsersOnline\x12\x1d.protobuf.QueryUsersOnlineReq\x1a\x1d.protobuf.QueryUsersOnlineRsp\"\x00\x42,\n\x19io.grpc.examples.protobufB\rProtobufProtoP\x01\x62\x06proto3'
)




_QUERYUSERSONLINEREQ = _descriptor.Descriptor(
  name='QueryUsersOnlineReq',
  full_name='protobuf.QueryUsersOnlineReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='appId', full_name='protobuf.QueryUsersOnlineReq.appId', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='userId', full_name='protobuf.QueryUsersOnlineReq.userId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=83,
)


_QUERYUSERSONLINERSP = _descriptor.Descriptor(
  name='QueryUsersOnlineRsp',
  full_name='protobuf.QueryUsersOnlineRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='retCode', full_name='protobuf.QueryUsersOnlineRsp.retCode', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='errMsg', full_name='protobuf.QueryUsersOnlineRsp.errMsg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='online', full_name='protobuf.QueryUsersOnlineRsp.online', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=155,
)


_SENDMSGREQ = _descriptor.Descriptor(
  name='SendMsgReq',
  full_name='protobuf.SendMsgReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='seq', full_name='protobuf.SendMsgReq.seq', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='appId', full_name='protobuf.SendMsgReq.appId', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='userId', full_name='protobuf.SendMsgReq.userId', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cms', full_name='protobuf.SendMsgReq.cms', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='protobuf.SendMsgReq.type', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='msg', full_name='protobuf.SendMsgReq.msg', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='isLocal', full_name='protobuf.SendMsgReq.isLocal', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=157,
  serialized_end=270,
)


_SENDMSGRSP = _descriptor.Descriptor(
  name='SendMsgRsp',
  full_name='protobuf.SendMsgRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='retCode', full_name='protobuf.SendMsgRsp.retCode', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='errMsg', full_name='protobuf.SendMsgRsp.errMsg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sendMsgId', full_name='protobuf.SendMsgRsp.sendMsgId', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=272,
  serialized_end=336,
)


_SENDMSGALLREQ = _descriptor.Descriptor(
  name='SendMsgAllReq',
  full_name='protobuf.SendMsgAllReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='seq', full_name='protobuf.SendMsgAllReq.seq', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='appId', full_name='protobuf.SendMsgAllReq.appId', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='userId', full_name='protobuf.SendMsgAllReq.userId', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cms', full_name='protobuf.SendMsgAllReq.cms', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='protobuf.SendMsgAllReq.type', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='msg', full_name='protobuf.SendMsgAllReq.msg', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=338,
  serialized_end=437,
)


_SENDMSGALLRSP = _descriptor.Descriptor(
  name='SendMsgAllRsp',
  full_name='protobuf.SendMsgAllRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='retCode', full_name='protobuf.SendMsgAllRsp.retCode', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='errMsg', full_name='protobuf.SendMsgAllRsp.errMsg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sendMsgId', full_name='protobuf.SendMsgAllRsp.sendMsgId', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=439,
  serialized_end=506,
)


_GETUSERLISTREQ = _descriptor.Descriptor(
  name='GetUserListReq',
  full_name='protobuf.GetUserListReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='appId', full_name='protobuf.GetUserListReq.appId', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=508,
  serialized_end=539,
)


_GETUSERLISTRSP = _descriptor.Descriptor(
  name='GetUserListRsp',
  full_name='protobuf.GetUserListRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='retCode', full_name='protobuf.GetUserListRsp.retCode', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='errMsg', full_name='protobuf.GetUserListRsp.errMsg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='userId', full_name='protobuf.GetUserListRsp.userId', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=541,
  serialized_end=606,
)

DESCRIPTOR.message_types_by_name['QueryUsersOnlineReq'] = _QUERYUSERSONLINEREQ
DESCRIPTOR.message_types_by_name['QueryUsersOnlineRsp'] = _QUERYUSERSONLINERSP
DESCRIPTOR.message_types_by_name['SendMsgReq'] = _SENDMSGREQ
DESCRIPTOR.message_types_by_name['SendMsgRsp'] = _SENDMSGRSP
DESCRIPTOR.message_types_by_name['SendMsgAllReq'] = _SENDMSGALLREQ
DESCRIPTOR.message_types_by_name['SendMsgAllRsp'] = _SENDMSGALLRSP
DESCRIPTOR.message_types_by_name['GetUserListReq'] = _GETUSERLISTREQ
DESCRIPTOR.message_types_by_name['GetUserListRsp'] = _GETUSERLISTRSP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

QueryUsersOnlineReq = _reflection.GeneratedProtocolMessageType('QueryUsersOnlineReq', (_message.Message,), {
  'DESCRIPTOR' : _QUERYUSERSONLINEREQ,
  '__module__' : 'im_protobuf_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.QueryUsersOnlineReq)
  })
_sym_db.RegisterMessage(QueryUsersOnlineReq)

QueryUsersOnlineRsp = _reflection.GeneratedProtocolMessageType('QueryUsersOnlineRsp', (_message.Message,), {
  'DESCRIPTOR' : _QUERYUSERSONLINERSP,
  '__module__' : 'im_protobuf_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.QueryUsersOnlineRsp)
  })
_sym_db.RegisterMessage(QueryUsersOnlineRsp)

SendMsgReq = _reflection.GeneratedProtocolMessageType('SendMsgReq', (_message.Message,), {
  'DESCRIPTOR' : _SENDMSGREQ,
  '__module__' : 'im_protobuf_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.SendMsgReq)
  })
_sym_db.RegisterMessage(SendMsgReq)

SendMsgRsp = _reflection.GeneratedProtocolMessageType('SendMsgRsp', (_message.Message,), {
  'DESCRIPTOR' : _SENDMSGRSP,
  '__module__' : 'im_protobuf_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.SendMsgRsp)
  })
_sym_db.RegisterMessage(SendMsgRsp)

SendMsgAllReq = _reflection.GeneratedProtocolMessageType('SendMsgAllReq', (_message.Message,), {
  'DESCRIPTOR' : _SENDMSGALLREQ,
  '__module__' : 'im_protobuf_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.SendMsgAllReq)
  })
_sym_db.RegisterMessage(SendMsgAllReq)

SendMsgAllRsp = _reflection.GeneratedProtocolMessageType('SendMsgAllRsp', (_message.Message,), {
  'DESCRIPTOR' : _SENDMSGALLRSP,
  '__module__' : 'im_protobuf_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.SendMsgAllRsp)
  })
_sym_db.RegisterMessage(SendMsgAllRsp)

GetUserListReq = _reflection.GeneratedProtocolMessageType('GetUserListReq', (_message.Message,), {
  'DESCRIPTOR' : _GETUSERLISTREQ,
  '__module__' : 'im_protobuf_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.GetUserListReq)
  })
_sym_db.RegisterMessage(GetUserListReq)

GetUserListRsp = _reflection.GeneratedProtocolMessageType('GetUserListRsp', (_message.Message,), {
  'DESCRIPTOR' : _GETUSERLISTRSP,
  '__module__' : 'im_protobuf_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.GetUserListRsp)
  })
_sym_db.RegisterMessage(GetUserListRsp)


DESCRIPTOR._options = None

_ACCSERVER = _descriptor.ServiceDescriptor(
  name='AccServer',
  full_name='protobuf.AccServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=608,
  serialized_end=703,
  methods=[
  _descriptor.MethodDescriptor(
    name='QueryUsersOnline',
    full_name='protobuf.AccServer.QueryUsersOnline',
    index=0,
    containing_service=None,
    input_type=_QUERYUSERSONLINEREQ,
    output_type=_QUERYUSERSONLINERSP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ACCSERVER)

DESCRIPTOR.services_by_name['AccServer'] = _ACCSERVER

# @@protoc_insertion_point(module_scope)
